apiVersion: v1
kind: Pod
metadata:
  labels:
    run: centos-faust
  name: centos-faust
spec:
  containers:
  - image: leehs1979/centos7httpd:v1
    name: centos-faust
    securityContext:
      privileged: true
    resources: {}
    imagePullPolicy: Always
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
