apiVersion: v1
kind: Service
metadata:
  name: streamlog-lb
  labels:
    app: streamlog
spec:
  ports:
    - port: 6068
      targetPort: 6068
      name: http
  selector:
    app: streamlog
  type: LoadBalancer